server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456Wn
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  redis:
    host: redis
    port: 6379
    timeout: 2000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto